trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: AppSigning

jobs:
- job: 'BuildApp'

  steps:
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
    displayName: 'Select the Xamarin SDK version'
    enabled: false

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: XamariniOS@2
    inputs:
      solutionFile: '**/*.sln'
      configuration: 'Debug'
      clean: true
      packageApp: false
      buildForSimulator: true
      runNugetRestore: false
      args: '-m'
    displayName: 'Debug build'

- job: 'PackageApp'
  dependsOn: 'BuildApp'

  steps:
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
    displayName: 'Select the Xamarin SDK version'
    enabled: false

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'DevCertificate.p12'
      certPwd: $(certificate.Password)
      keychain: 'temp'
    displayName: 'Install Apple Developer Certificate'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'profile_application.mobileprovision'
    displayName: 'Install provisioning profile for App'

  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'profile_extension.mobileprovision'
    displayName: 'Install provisioning profile for App Extension'

  - task: XamariniOS@2
    inputs:
      solutionFile: '**/*.sln'
      configuration: 'Release'
      clean: true
      packageApp: true
      runNugetRestore: false
      args: '-m'
    displayName: 'Release build (sign and package)'
