
stages:
  - stage: 'MacOS_AppCenter_Mojave'
    jobs:
    - job: 'macos1015'
      pool:
        vmImage: 'macos-latest'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK: ''
            XCODE_VERSION: ''
      steps:
      - template: src/xamarin-ios/templates/test-xamarin-ios-using-ui-test.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          XCODE_VERSION: $(XCODE_VERSION)
